# Generated by Django 4.0.4 on 2022-09-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='type',
            new_name='type_id',
        ),
    ]
