# Generated by Django 4.0.4 on 2022-09-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_rename_category_robot_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='category_id',
            new_name='category',
        ),
    ]
