# Generated by Django 4.0.4 on 2022-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_album_robot_robotcategory_robottype_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
