# Generated by Django 4.0.4 on 2022-09-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0003_alter_robot_created_at_alter_robot_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='type_id',
            new_name='type',
        ),
    ]
