# Generated by Django 4.0.4 on 2022-09-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0003_rename_category_id_robot_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='type_id',
            new_name='type',
        ),
    ]
