# Generated by Django 4.0.4 on 2022-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0004_rename_category_id_robot_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
